config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'posts#create'
  # get '/posts/:id/edit', to: 'posts#edit'
  # patch '/posts/:id', to: 'posts#update'
  # delete 'posts/:od' to: 'posts#destroy'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote #/posts/3/vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :users, only: [:show, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]
  before_action :set_comment, only: [:vote]
  before_action :require_user
  
  def create
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find params[:id]
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
            flash[:notice] = "Your vote was counted."
        else
            flash[:error] = "You can only vote on a post once."
        end

        redirect_to :back
      end
      format.js
    end
  end

  private
    def set_post
      @post = Post.find_by slug: params[:post_id]
    end

    def set_comment
      @comment = Comment.find params[:id]
    end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: :post, remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
    <span id='comment_<%= comment.id %>_votes'><%= comment.total_votes %></span>
    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: :post, remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>

  <div class='span8 well'>
    <em><p>"<%= comment.body %>"</em> 
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </p>
    <span class='quiet'>by </span><%= link_to comment.creator.username, user_path(comment.creator) %> <small>at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/_form.html.erb
<h5>Leave a comment:</h5>
<%= render 'shared/errors', errors: @comment.errors %>
<%= form_for [@post, @comment] do |f| %> <!-- nests the comments under posts -->
  <%= f.text_area :body, rows: 3, class: 'span4' %>
  <br/>
  <%= f.submit 'Create comment', class: 'btn btn-submit btn-primary' %>
<% end %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %>');
<% else %>
  alert('You can only vote on a comment once.');
<% end %>