config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'posts#create'
  # get '/posts/:id/edit', to: 'posts#edit'
  # patch '/posts/:id', to: 'posts#update'
  # delete 'posts/:od' to: 'posts#destroy'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote #/posts/3/vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :users, only: [:show, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'twilio-ruby'
  include Sluggable

  has_many :posts
  has_many :comments
  has_many :votes
  
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates_format_of :username, with: /\A[a-z][a-z0-9_]*[a-z0-9]\z/, message: "must contain only lowercase letters, numbers, and underscores"
  validates :password, presence: true, confirmation: true, length: {minimum: 5}, on: :create
  validates_format_of :phone, with: /\A\d{10}\z/, message: "must be 10 digits"

  sluggable_column :username

  def two_factor_auth?
    !self.phone.blank?
  end

  def generate_pin!
    self.update_column(:pin, rand(10 ** 6)) # random 6 digit number
  end

  def remove_pin!
    self.update_column(:pin, nil) # random 6 digit number
  end

  def send_pin_to_twilio!
    # put your own credentials here 
    account_sid = ENV['TWILIO_API_KEY']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
     
    # set up a client to talk to the Twilio REST API 
    client = Twilio::REST::Client.new account_sid, auth_token 

    client.account.messages.create({
      :from => '+14157921434', 
      :to => '+1' + self.phone, 
      :body => 'Hello, here is your PostIt! authorization PIN: ' + self.pin.to_s
    })
  end

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]


  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    # pattern, setup 
    @user = User.new(user_params) # created private method to sanitize parameters

    if @user.save
      flash[:notice] = "Your user was created."
      session[:user_id] = @user.id
      redirect_to :root
    else #validation error
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your user was saved."
      redirect_to user_path(@user)
    else #validation error
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :time_zone, :phone)
      # requires the top level key to be :user
      # permits with bang allows all attributes
      # rails 3 uses attr_accessible in the model
    end

    def set_user
      @user = User.find_by slug: params[:id]
    end

    def require_same_user
      if current_user != @user
        flash[:error] = "You are not allowed to do that."
        redirect_to user_path = @user
      end
    end
end

app/views/users/_form.html.erb
<div class='well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class='control-group'>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
    </div>

    <div class='control-group'>
      <%= f.label :phone, "Phone Number <small>(numbers only)</small>".html_safe %>
      <%= f.text_field :phone, maxlength: 10 %>
      <%= link_to '#', id: 'two_factor_phone' do %>
        <i class='icon-question-sign'></i>
      <% end %>
    </div>


    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class='row'>
  <div class='span8 well'>
    <h4><%= link_to user.username, user_path(user) %></h4>
    <p>
      <span class='quiet'>has </span><small><%= "#{pluralize(user.posts.size,'Post')}" %></small>
    </p>
    <span class='quiet'>joined </span><small><%= user.created_at %></small>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit user' %>
<%= render 'shared/errors', errors: @user.errors %>
<%= render 'form' %>

app/views/users/index.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; Users".html_safe %>

<%= render 'shared/content_title', title: header %>
<%= render @users %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Create a new user' %>
<%= render 'shared/errors', errors: @user.errors %>
<%= render 'form' %>

app/views/users/show.html.erb
<% header = link_to('All Posts', posts_path) + (" &raquo; " + link_to('Users', users_path) + " &raquo; #{@user.username}").html_safe %>

<%= render 'shared/content_title', title: header %>
<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Time zone:</dt>
    <dd><%= @user.time_zone %></dd>
    <dt>Phone:</dt>
    <dd><%= @user.phone %></dd>
  </dl>
</div>
<hr>
<h4><%= @user.username %>'s activity</h4>
<ul class="nav nav-tabs">
  <li role="presentation" class='<%= 'active' if params[:tab].nil? %>'><%= link_to "Posts (#{@user.posts.size})", user_path(@user) %></li>
  <li role="presentation" class='<%= 'active' if params[:tab] == 'comments' %>'><%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %></li>
</ul>

<%= render @user.posts if params[:tab].nil? %>
<%= render @user.comments, show_post: true if params[:tab] == 'comments' %>

<%= link_to "back to users", users_path %>