config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'posts#create'
  # get '/posts/:id/edit', to: 'posts#edit'
  # patch '/posts/:id', to: 'posts#update'
  # delete 'posts/:od' to: 'posts#destroy'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote #/posts/3/vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :users, only: [:show, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse

    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml { render xml: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    # pattern, setup 
    @post = Post.new(post_params) # created private method to sanitize parameters
    @post.creator = current_user # TODO change once we add authentication
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to post_path(@post)
    else #validation error
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
        format.html do
          if @vote.valid?
            flash[:notice] = "Your vote was counted."
          else
            flash[:error] = "You can only vote on a post once."
          end

          redirect_to :back
        end
        format.js
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
      # requires the top level key to be :post
      # permits with bang allows all attributes
      # rails 3 uses attr_accessible in the model
    end

    def set_post
      @post = Post.find_by slug: params[:id]
    end

    def require_creator
      access_denied unless logged_in? && (current_user == @post.creator || current_user.admin?)
    end 
end

app/views/posts/_form.html.erb
<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>

    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id='post_<%= post.to_param %>_errors' class='row' style="display: none">
  <div class='alert alert-error span8'>
    You can only vote once!
  </div>
</div>

<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: :post, remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>

    <span id='post_<%= post.to_param %>_votes'><%= post.total_votes %></span>
    
    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_path(post, vote: false), method: :post, remote: true  do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, external_link(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %> <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small><span><%= link_to "#{pluralize(post.comments.size, 'comment')}", post_path(post) %></span></small>
    <br/>
    <% if logged_in? %>
      <small><%= link_to "Edit post", edit_post_path(post) %></small>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Post" %>
<%= render 'shared/errors', errors: @post.errors %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% if @posts.any? %>
  <%= render @posts %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'shared/errors', errors: @post.errors %>
<%= render 'form' %>

app/views/posts/show.html.erb
<p><%= render @post.categories %></p>
<%= render 'shared/content_title', title: @post.title %>

<% if @post.description %>
  <p><%= @post.description %></p>
  <hr>
<% end %>

<% if logged_in? %>
  <%= render 'comments/form' %>
<% end %>

<% if @post.comments.any? %>
  <p><strong>Comments:</strong></p>
  <%= render @post.reload.comments.sort_by{|x| x.total_votes}.reverse %>
<% end %>

<%= link_to 'back to posts index', posts_path %>
[<%= link_to "edit", edit_post_path(@post) %>]

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.to_param %>_votes').html('<%= @post.total_votes %>');
<% else %>
  // alert('You can only vote on each post once.')
  $('#post_<%= @post.to_param %>_errors').show();
<% end %>